language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - phpize
  - ./configure --enable-opcache
  - make

script:
  - php -d zend_extension=`pwd`/modules/opcache.so -m | grep "Zend OPcache"
